export const fontFamilyNames = [
  { name: 'Arial' },
  { name: 'Georgia' },
  { name: 'Roboto' },
  { name: 'Roboto Slab' },
  { name: 'Times New Roman' },
  { name: 'Raleway' },
  { name: 'Playfair Display' },
  { name: 'Lora' },
  { name: 'Dancing Script' },
  { name: 'MuseoModerno' },
  { name: 'Public Sans' },
  { name: 'Open Sans Condensed' },
  { name: 'Work Sans' },
  { name: 'Titillium Web' },
  { name: 'Anton' },
  { name: 'Yanone Kaffeesatz' },
  { name: 'Lobster' },
  { name: 'Bebas Neue' },
  { name: 'Fjalla One' },
  { name: 'Abel' },
  { name: 'Barlow Condensed' },
  { name: 'Overpass' },
  { name: 'Teko' },
  { name: 'Pacifico' }
];
